In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import os 
import glob
import time
import datetime as dt
import numpy as np
import pandas as pd

In [0]:
os.chdir(r"/content/drive/My Drive/work/test-exam-data/code/exam_2")

In [0]:
data=pd.read_csv("/content/drive/My Drive/work/test-exam-data/code/exam_2/CancerRadiomicsKaggle_v2_050620.csv") ##Load Data

In [0]:
##drop column with no character of Patient such as PatientID,Time to event,Patient Status Since we want to predict only Patient
##Status at 3 Year

data=data.drop(['Patient ID','Time to Event','Patient Status'],axis=1)

In [0]:
#since the data contain  Unknown Patient Status we drop it cause unknown ground truth for status at 3 Year
data=data[data['Patient Status at 3 Year']!=-1]

In [0]:
#start by define dependant variable with y and independant with x
y= data.iloc[:,6]
x=data.drop('Patient Status at 3 Year',axis=1)

In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42) #split train and test set

In [9]:
# Instantiate model with 100 decision trees
rf = RandomForestClassifier(n_estimators = 1000, random_state = 42,min_samples_leaf=1, min_samples_split=2,max_depth=8)
# Train the model on training data
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=8, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [0]:
predictions = rf.predict(X_test) ##test_predictions on X_test of random forest

In [11]:
##random forest result 

from sklearn.metrics import classification_report
from sklearn import metrics
print(metrics.confusion_matrix(y_test, predictions, labels=[0,1]))
print(classification_report(y_test, predictions))

[[28  5]
 [ 5  1]]
              precision    recall  f1-score   support

           0       0.85      0.85      0.85        33
           1       0.17      0.17      0.17         6

    accuracy                           0.74        39
   macro avg       0.51      0.51      0.51        39
weighted avg       0.74      0.74      0.74        39



In [0]:
#now we use neuron network 
from sklearn.preprocessing import StandardScaler

# Define the scaler 
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
# Import `Sequential` from `keras.models`
from keras.models import Sequential

# Import `Dense` from `keras.layers`
from keras.layers import Dense

# Initialize the constructor
model = Sequential()

# Add an input layer 
model.add(Dense(12, activation='relu', input_shape=(848,)))

# Add one hidden layer 
model.add(Dense(8, activation='relu'))

# Add an output layer 
model.add(Dense(1, activation='sigmoid'))

Using TensorFlow backend.


In [14]:
# Model output shape
model.output_shape

# Model summary
model.summary()

# Model config
model.get_config()

# List all weight tensors 
model.get_weights()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 12)                10188     
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 10,301
Trainable params: 10,301
Non-trainable params: 0
_________________________________________________________________


[array([[-0.0460181 , -0.07718966, -0.00146335, ...,  0.04643925,
         -0.03638259,  0.03699494],
        [-0.00901884,  0.03629152, -0.01115523, ...,  0.01028433,
         -0.05809089,  0.00427084],
        [-0.00450379, -0.00827155, -0.0067997 , ...,  0.06445467,
          0.01527549, -0.07860541],
        ...,
        [ 0.08038493,  0.04923782,  0.03887641, ..., -0.03521533,
         -0.06512478, -0.00422085],
        [ 0.036571  ,  0.02415945,  0.01164429, ..., -0.02402423,
          0.01178158, -0.07302893],
        [ 0.06791995,  0.0448193 , -0.01229811, ...,  0.02089168,
          0.03051031, -0.01421087]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.2930793 ,  0.02336347, -0.21657673, -0.18915012, -0.22530177,
          0.0876832 , -0.42767948, -0.00672549],
        [ 0.33524954, -0.4391479 , -0.2933931 , -0.26068047, -0.28418213,
         -0.04288042,  0.5211166 ,  0.12941873],
        [-0.40302563, -0.11369553,  0.0

In [15]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
                   
model.fit(X_train, y_train,epochs=20, batch_size=1, verbose=1)

Epoch 1/20
156/156 [==============================] - 0s 2ms/step - loss: 0.5307 - accuracy: 0.7949
Epoch 2/20
156/156 [==============================] - 0s 1ms/step - loss: 0.3402 - accuracy: 0.8397
Epoch 3/20
156/156 [==============================] - 0s 1ms/step - loss: 0.3491 - accuracy: 0.8782
Epoch 4/20
156/156 [==============================] - 0s 1ms/step - loss: 0.2898 - accuracy: 0.8269
Epoch 5/20
156/156 [==============================] - 0s 1ms/step - loss: 0.2426 - accuracy: 0.8910
Epoch 6/20
156/156 [==============================] - 0s 1ms/step - loss: 0.1956 - accuracy: 0.9038
Epoch 7/20
156/156 [==============================] - 0s 1ms/step - loss: 0.1788 - accuracy: 0.9103
Epoch 8/20
156/156 [==============================] - 0s 1ms/step - loss: 0.1695 - accuracy: 0.9167
Epoch 9/20
156/156 [==============================] - 0s 1ms/step - loss: 0.1556 - accuracy: 0.9167
Epoch 10/20
156/156 [==============================] - 0s 1ms/step - loss: 0.1234 - accuracy: 0.9551

In [0]:
y_pred = model.predict(X_test) ##predict y_pred with neuron network model

In [0]:
y_pred=(y_pred >0.05).astype(int) ##we try different treshold and choose treshold that make f1-score class 1 is at max

In [18]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, y_pred, labels=[0,1]))

[[24  9]
 [ 3  3]]


In [19]:
#result of neuron network 

from sklearn.metrics import classification_report
target_names = ['class 0', 'class 1']
print(classification_report(y_test, y_pred, target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.89      0.73      0.80        33
     class 1       0.25      0.50      0.33         6

    accuracy                           0.69        39
   macro avg       0.57      0.61      0.57        39
weighted avg       0.79      0.69      0.73        39

